"Defeat",
"Small Bright .1 Sec",
"Small Bright .2 Sec",
"Small Bright .3 Sec",
"Medium Warm 1.1 Sec",
"Medium Bright .6 Sec",
"Large Bright 1.2 Sec",
"Large Dark 1.0 Sec",
"Medium Dark .6 Sec",
"Medium Dark .5 Sec",
"Medium Bright .6 Sec",
"Medium Bright .8 Sec",
"Large Warm 1.0 Sec",
"Large Warm 1.1 Sec",
"Medium Dark 1.0 Sec",
"Medium Bright 1.1 Sec",
"Medium Bright 1.15 Sec",
"Large Bright 1.6 Sec",
"Large Dark 1.7 Sec",
"Medum Bright 1.65 Sec",
"Medium Bright 1.9 Sec",
"Large Warm 2.2 Sec",
"Large Warm 1.75 Sec",
"Large Bright 1.45 Sec",
"Large Dark 2.2 Sec",
"Large Warm 2.3 Sec",
"Large Bright 2.4 Sec",
"Large Bright 2.5 Sec",
"Xlarge Warm 5.0 Sec",
"Xlarge Warm 15.0 Sec",
"Slow Gate 100 Msec",
"Slow Gate 200 Msec",
"Slow Gate 250 Msec",
"Slow Gate 400 Msec",
"Slow Gate 450 Msec",
"Fast Gate 150 Msec",
"Fast Gate 75 Msec",
"Fast Gate 200 Msec",
"Fast Gate 100 Msec",
"Fast Gate 175 Msec",
"Reverse 400 Msec",
"Reverse 450 Msec",
"Reverse 250 Msec",
"Reverse 200 Msec",
"Reverse 150 Msec",
"Bloom 1 8 Sec",
"Reverse 500 Msec",
"Reverse Regen. 2 Sec",
"Reverse Regen. 8 Sec",
"Bloom 2 7 Sec",
"Triggered Flange",
"Flange Pan 1",
"Flange Pan 2",
"Triggered Flange 2",
"Flange Pan 3",
"Flange Pan 4",
"Flange Pan 5",
"Triggered Flange 3",
"Flange Pan 6",
"Flange Pan 7",
"Light Chorus 1",
"Light Chorus 2",
"Medium Chorus 1",
"Medium Chorus 2",
"Medium Chorus 3",
"Deep Chorus 1",
"Deep Chorus 2",
"Deep Chorus 3",
"Fast Chorus 1",
"Fast Chorus 2",
"35 Msec",
"55 Msec",
"75 Msec",
"115 Msec",
"140 Msec",
"155 Msec",
"160 Msec",
"170 Msec",
"175 Msec",
"180 Msec",
"185 Msec",
"195 Msec",
"205 Msec",
"210 Msec",
"220 Msec",
"240 Msec",
"250 Msec",
"275 Msec",
"375 Msec",
"460 Msec",
"2 Tap Ambient",
"3 Tap Pan",
"Multitap",
"Multitap Reverse Pan",
"Thickener/frozen Flange",
"Stereo Generation",
"Stereo Generation Wide",
"Regenerated Delay 2 Sec",
"Regenerated Delay 3 Sec",
"Regenerated Delay 4 Sec",
